export const products = [
  {
    id: 1,
    title: "Apple 10+",
    description: "black in color",
    price: 2500,
    img: "/images/item1.jpg",
    quantity: 1,
  },
  {
    id: 2,
    title: "HeadPhone QKZ",
    description: "black in color",
    price: 230,
    img: "/images/item2.jpg",
    quantity: 1,
  },
  {
    id: 3,
    title: "College Bag",
    description: "blue in color",
    price: 3500,
    img: "/images/item3.jpg",
    quantity: 1,
  },
  {
    id: 4,
    title: "Watch 11",
    description: "white in color",
    price: 90500,
    img: "/images/item4.jpg",
    quantity: 1,
  },
  {
    id: 5,
    title: "By Cycle",
    description: "black in color",
    price: 2500,
    img: "/images/item5.jpg",
    quantity: 1,
  },
];
